on: push
name: Build
jobs:
  checks:
    name: run
    runs-on: ubuntu-latest
    steps:
    - name: install golang
      uses: actions/setup-go@v3
      with:
        go-version: '1.20.1'

    - name: install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - uses: actions/checkout@v3

    - name: build Linux amd64
      run: make nightlight_linux_amd64

    - name: run vulnerability check
      run: govulncheck ./...

    - name: tests
      run: make tests

    - name: upload Linux amd64 build
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: nightlight_linux_amd64

    - name: build Linux arm7 (Raspberry Pi 32-bit)
      run: make nightlight_linux_arm7

    - name: upload Linux arm7 (Raspberry Pi 32-bit) build
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: nightlight_linux_arm7

    - name: build Linux arm64 (Raspberry Pi 64-bit)
      run: make nightlight_linux_arm64

    - name: upload Linux arm64 (Raspberry Pi 64-bit) build
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: nightlight_linux_arm64

    - name: build Darwin amd64 (MacOS Intel)
      run: make nightlight_darwin_amd64

    - name: upload Darwin amd64 (MacOS Intel) build
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: nightlight_darwin_amd64

    - name: build Darwin arm64 (MacOS Apple Silicon)
      run: make nightlight_darwin_arm64

    - name: upload Darwin arm64 (MacOS Apple Silicon) build
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: nightlight_darwin_arm64

    - name: build Windows amd64
      run: make nightlight_windows_amd64

    - name: upload windows build
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: nightlight_windows_amd64.exe
